config/routes.rb
Chik::Application.routes.draw do
  resources :downloads

  resources :images

  resources :enquiries

  get "contact/index"
  resources :buy_actions

  resources :involvement_actions

  resources :events

  resources :background_images

  get "admin" => 'admin#index'
  resources :content_items

  root :to => "home#index"
  devise_for :users, :controllers => {:registrations => "registrations"}
  resources :users
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user 
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. 
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/background_image.rb
class BackgroundImage < ActiveRecord::Base
	default_scope order: 'background_images.priority ASC'
	
	def self.active
		BackgroundImage.where('priority > ?', 0)
	end

	mount_uploader :image, BackgroundImageUploader

	validates_presence_of :priority, :image
end

app/models/buy_action.rb
class BuyAction < ActiveRecord::Base
	default_scope order: 'buy_actions.priority ASC'
	
	def self.active
		BuyAction.where('priority > ?', '0')
	end
end

app/models/content_item.rb
class ContentItem < ActiveRecord::Base
end

app/models/download.rb
class Download < ActiveRecord::Base
end

app/models/enquiry.rb
class Enquiry < ActiveRecord::Base
	validates_presence_of :name, :email, :message
	default_scope order: 'enquiries.created_at DESC'
end

app/models/event.rb
class Event < ActiveRecord::Base
	def self.future
		Event.where("date >= ?", Date.today)
	end

	default_scope order: 'events.date ASC'
end

app/models/image.rb
class Image < ActiveRecord::Base
	mount_uploader :image, PhotoGalleryUploader
end

app/models/involvement_action.rb
class InvolvementAction < ActiveRecord::Base
	default_scope order: 'involvement_actions.priority ASC'
	
	def self.active
		InvolvementAction.where('priority > ?', '0')
	end
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users, :join_table => :users_roles
  belongs_to :resource, :polymorphic => true
  
  scopify
end

app/models/user.rb
class User < ActiveRecord::Base
  rolify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	layout 'home'
  def index
    @content_item = ContentItem.first
    @event = Event.future.first
    @background_images = BackgroundImage.active
    @buy_actions = BuyAction.active
    @involvement_actions = InvolvementAction.active
    @enquiry = Enquiry.new
    @background_images = BackgroundImage.active
    @images = Image.all
    @downloads = Download.all
  end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

  def display_base_errors resource
    return '' if (resource.errors.empty?) or (resource.errors[:base].empty?)
    messages = resource.errors[:base].map { |msg| content_tag(:p, msg) }.join
    html = <<-HTML
    <div class="alert alert-error alert-block">
      <button type="button" class="close" data-dismiss="alert">&#215;</button>
      #{messages}
    </div>
    HTML
    html.html_safe
  end

end

app/helpers/buy_actions_helper.rb
module BuyActionsHelper
end

app/helpers/downloads_helper.rb
module DownloadsHelper
end

app/helpers/enquiries_helper.rb
module EnquiriesHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/views/admin/_background_images.html.erb
<h3>Background images</h3>
		
		<div class="well">
		<% if @background_images %>
			<table class="table">
				<tr>
					<th>Image</th>
					<th>Priority</th>
					<th></th>
					<th></th>
				</tr>
				<% @background_images.each do |background_image| %>
					<tr>
						<td><%= link_to background_image.image.url, target: "_blank" do %><%= image_tag background_image.image.url, class: 'img-thumbnail bg-img-list' %><% end %></td>
						<td><%= background_image.priority %></td>
						<td><%= link_to "Edit", edit_background_image_path(background_image) %></td>
						<td><%= link_to 'Delete', background_image, method: :delete, data: { confirm: 'Are you sure?' } %></td>
					</tr>
				<% end %>
			</table>
		<% else %>
			<p>No background images uploaded.</p>
		<% end %>
		<%= link_to 'Add new background image', new_background_image_path, class: 'btn btn-success btn-block' %>
		</div>
		<br>

app/views/admin/_buy_actions.html.erb
<h3>Purchase Options</h3>

<div class="well">
<table class="table">
	<tr>
		<th>Title</th>
		<th>Priority</th>
		<th></th>
		<th></th>
	</tr>
	<% @buy_actions.each do |buy_action| %>
		<tr>
			<td><%= buy_action.title %></td>
			<td><%= buy_action.priority %></td>
			<td><%= link_to "Edit", edit_buy_action_path(buy_action) %></td>
			<td><%= link_to 'Delete', buy_action, method: :delete, data: { confirm: 'Are you sure?' } %></td>
		</tr>
	<% end %>
</table>
<br>
<%= link_to "Add purchase option", new_buy_action_path, class: 'btn btn-success btn-block' %>
</div>
<br>

app/views/admin/_downloads.html.erb
<h3>Downloads</h3>

<div class="well">
<table class="table">
	<tr>
		<th>Title</th>
		<th>File link</th>
		<th></th>
		<th></th>
	</tr>
	<% @downloads.each do |download| %>
		<tr>
			<td><%= download.name %></td>
			<td><%= link_to 'Link', download.file %></td>
			<td><%= link_to "Edit", edit_download_path(download) %></td>
			<td><%= link_to 'Delete', download, method: :delete, data: { confirm: 'Are you sure?' } %></td>
		</tr>
	<% end %>
</table>
<%= link_to 'Add new download', new_download_path, class: 'btn btn-success btn-block' %>
</div>
<br>

app/views/admin/_enquiries.html.erb
<h3>Enquiries</h3>

<div class="well">
	<p>Number of enquiries: <%= Enquiry.all.count %></p>
	<%= link_to "View enquiries", enquiries_path, class: 'btn btn-success' %>
</div>

app/views/admin/_events.html.erb
<h3>Events</h3>

<div class="well">
<table class="table">
	<tr>
		<th>Title</th>
		<th>Date</th>
		<th></th>
		<th></th>
	</tr>
	<% @events.each do |event| %>
		<tr>
			<td><%= event.title %></td>
			<td><%= event.date %></td>
			<td><%= link_to "Edit", edit_event_path(event) %></td>
			<td><%= link_to 'Delete', event, method: :delete, data: { confirm: 'Are you sure?' } %></td>
		</tr>
	<% end %>
</table>
<%= link_to 'Add new event', new_event_path, class: 'btn btn-success btn-block' %>
</div>
<br>

app/views/admin/_involvement_actions.html.erb
<h3>Get involved options</h3>
		
		<div class="well">
		<% if @involvement_actions %>
			<table class="table">
				<tr>
					<th>Title</th>
					<th>Priority</th>
					<th></th>
					<th></th>
				</tr>
				<% @involvement_actions.each do |involvement_action| %>
					<tr>
						<td><%= involvement_action.title %></td>
						<td><%= involvement_action.priority %></td>
						<td><%= link_to "Edit", edit_involvement_action_path(involvement_action) %></td>
						<td><%= link_to 'Delete', involvement_action, method: :delete, data: { confirm: 'Are you sure?' } %></td>
					</tr>
				<% end %>
			</table>
		<% else %>
			<p>There are no get involved options.</p>
		<% end %>
		<%= link_to 'Add new option', new_involvement_action_path, class: 'btn btn-success btn-block' %>
		</div>
		<br>

app/views/admin/index.html.erb
<div class="row">
	<div class="col-md-12">
		<h1>The Chikukwa Project: Control Centre <span class="pull-right"><%= link_to "View site", root_path, class: 'btn btn-success' %> <%= link_to "Change password", edit_registration_path(current_user), class: 'btn btn-warning' %></span></h1>
	</div>
</div>
<div class="row">
	<div class="col-md-6">
		<h3>Edit main content </h3>
		<div class="well">
			<%= render 'content_items/form' %>
		</div>
		<h3>Images for photo gallery</h3>
		<div class="well">
			<% if @images %>
				<table class="table table-hover">
					<% @images.each do |image| %>
					<tr>
						<td><%= image_tag image.image, width: '150px' %></td>
						<td><%= image.caption %></td>
						<td><%= link_to 'Edit', edit_image_path(image) %></td>
        				<td><%= link_to 'Destroy', image, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        			</tr>
        			<% end %>
        		</table>
        	<% end %>
        	<hr>
        	<h4>Add image</h4>

			<%= render 'images/form' %>
		</div>

	</div>
	<div class="col-md-6">
		<%= render 'enquiries' %>
		<%= render 'buy_actions' %>
		<%= render 'involvement_actions' %>
		<%= render 'background_images' %>
		<%= render 'events' %>
		<%= render 'downloads' %>
		
		<br>
		

	</div>
</div>
<br>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    
      <%= content_tag :div, msg, :id => "flash_#{name}", class: 'navbar-text' %>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
      <span class="sr-only">Menu</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <%= link_to root_path, :class => 'navbar-brand' do %>
       The Chikukwa Project
    <% end %>
  </div>


  <!-- Collect the nav links, forms, and other content for toggling -->
  <!-- <div class="collapse navbar-collapse navbar-ex1-collapse pull-right">
    <ul class="nav navbar-nav">
      <li>
    </ul>
    <ul class="nav navbar-nav pull-right">
      <% if user_signed_in? %>

      
    <% if current_user.has_role? :admin %>
      <li>
      <%= link_to 'Admin', admin_path %>
      </li>
    <% end %>
    
  <% else %>
    <li>
    <%= link_to 'Login', new_user_session_path %>
    </li>
  <% end %>
  <% if user_signed_in? %>
    
    
      
  <% else %>
    <li>
    <%= link_to 'Sign up', new_user_registration_path %>
    </li>
  <% end %>
    </ul> -->
    <!-- <form class="navbar-form navbar-left" role="search">
      <div class="form-group">
        <input type="text" class="form-control" placeholder="Search">
      </div>
      <button type="submit" class="btn btn-default">Submit</button>
    </form> -->
   <!--  <ul class="nav navbar-nav navbar-right">
      
    </ul>  -->
  </div><!-- /.navbar-collapse -->

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Chik" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Chik" %>">
    <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.0.2/css/bootstrap.min.css">
    
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= yield(:head) %>
    <style>
      .bg-img-list {
        width: 100px;
      }
    </style>
  </head>
  <body>

  <div class="container">
    <br>
              <%= yield %>
  </div>
  <script>
  $(document).ready(function() {
    $('.ckeditor').ckeditor({
      // optional config
      config.toolbar = [
        [ 'Source', '-', 'Bold', 'Italic' ]
      ];
    });
  });
  </script>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Chik" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Chik" %>">
    <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.0.2/css/bootstrap.min.css">
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= yield(:head) %>
    <style>
      .bg-img-show {
        width: 400px;
      }
    </style>
  </head>
  <body>

  <div class="container">
    <div class="row">
      
        <%= yield %>
        
      
    </div>
  </div>
    
  </body>
</html>

app/views/layouts/enquiries.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Chik" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Chik" %>">
    <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.0.2/css/bootstrap.min.css">
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= yield(:head) %>
    <style>
      .bg-img-show {
        width: 400px;
      }
    </style>
  </head>
  <body>

  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <%= yield %>
        
      </div>
    </div>
  </div>
    
  </body>
</html>

app/views/layouts/home.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "The Chikukwa Project - a permaculture success story in Zimbabwe" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "An amazing story of African villagers who turned their lives around. THE CHIKUKWA PROJECT is a feel good story out of Africa. For the last 20 years an incredible permaculture project has been growing in Zimbabwe." %>">
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= yield(:head) %>
    <style>
        <% @background_images.each_with_index do |background_image, index| %>
        .bgr-<%= index + 1 %> {
            background-image: url(<%= background_image.image.url %>);
        }
        <% end %>
        .panel-title {text-transform: uppercase;}
    </style>
    </head>
  <body>

              <%= yield %>
    <div class="footer"  data-no-turbolink>
    <%= link_to "admin", admin_path %>
    </div>
  </body>
</html>