config/routes.rb
Chik::Application.routes.draw do
  resources :downloads

  resources :images

  resources :enquiries

  get "contact/index"
  resources :buy_actions

  resources :involvement_actions

  resources :events

  resources :background_images

  get "admin" => 'admin#index'
  resources :content_items

  root :to => "home#index"
  devise_for :users, :controllers => {:registrations => "registrations"}
  resources :users
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user 
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. 
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/background_image.rb
class BackgroundImage < ActiveRecord::Base
	default_scope order: 'background_images.priority ASC'
	
	def self.active
		BackgroundImage.where('priority > ?', 0)
	end

	mount_uploader :image, BackgroundImageUploader

	validates_presence_of :priority, :image
end

app/models/buy_action.rb
class BuyAction < ActiveRecord::Base
	default_scope order: 'buy_actions.priority ASC'
	
	def self.active
		BuyAction.where('priority > ?', '0')
	end
end

app/models/content_item.rb
class ContentItem < ActiveRecord::Base
end

app/models/download.rb
class Download < ActiveRecord::Base
end

app/models/enquiry.rb
class Enquiry < ActiveRecord::Base
	validates_presence_of :name, :email, :message
	default_scope order: 'enquiries.created_at DESC'
end

app/models/event.rb
class Event < ActiveRecord::Base
	def self.future
		Event.where("date >= ?", Date.today)
	end

	default_scope order: 'events.date ASC'
end

app/models/image.rb
class Image < ActiveRecord::Base
	mount_uploader :image, PhotoGalleryUploader
end

app/models/involvement_action.rb
class InvolvementAction < ActiveRecord::Base
	default_scope order: 'involvement_actions.priority ASC'
	
	def self.active
		InvolvementAction.where('priority > ?', '0')
	end
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users, :join_table => :users_roles
  belongs_to :resource, :polymorphic => true
  
  scopify
end

app/models/user.rb
class User < ActiveRecord::Base
  rolify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
	layout 'layouts/admin'
	before_filter :authenticate_user!
  def index
  	@content_item = ContentItem.first
  	@background_images = BackgroundImage.all
  	@events = Event.all
  	@buy_actions = BuyAction.all
  	@involvement_actions = InvolvementAction.all
  	@users = User.all
    @image = Image.new
    @images = Image.all
    @download = Download.new
    @downloads = Download.all
  end
end

app/controllers/content_items_controller.rb
class ContentItemsController < ApplicationController
  before_filter :authenticate_user!
  before_action :set_content_item, only: [:show, :edit, :update, :destroy]

  # GET /content_items
  # GET /content_items.json
  def index
    @content_items = ContentItem.all
  end

  # GET /content_items/1
  # GET /content_items/1.json
  def show
  end

  # GET /content_items/new
  def new
    @content_item = ContentItem.new
  end

  # GET /content_items/1/edit
  def edit
  end

  # POST /content_items
  # POST /content_items.json
  def create
    @content_item = ContentItem.new(content_item_params)

    respond_to do |format|
      if @content_item.save
        format.html { redirect_to @content_item, notice: 'Content item was successfully created.' }
        format.json { render action: 'show', status: :created, location: @content_item }
      else
        format.html { render action: 'new' }
        format.json { render json: @content_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /content_items/1
  # PATCH/PUT /content_items/1.json
  def update
    respond_to do |format|
      if @content_item.update(content_item_params)
        format.html { redirect_to admin_path, notice: 'Content successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @content_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /content_items/1
  # DELETE /content_items/1.json
  def destroy
    @content_item.destroy
    respond_to do |format|
      format.html { redirect_to content_items_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_content_item
      @content_item = ContentItem.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def content_item_params
      params.require(:content_item).permit(:about, :quote, :quote_author, :twitter_widget_id, :trailer_iframe, :trailer_caption, :download_link, :download_image)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	layout 'home'
  def index
    @content_item = ContentItem.first
    @event = Event.future.first
    @background_images = BackgroundImage.active
    @buy_actions = BuyAction.active
    @involvement_actions = InvolvementAction.active
    @enquiry = Enquiry.new
    @background_images = BackgroundImage.active
    @images = Image.all
    @downloads = Download.all
  end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

  def display_base_errors resource
    return '' if (resource.errors.empty?) or (resource.errors[:base].empty?)
    messages = resource.errors[:base].map { |msg| content_tag(:p, msg) }.join
    html = <<-HTML
    <div class="alert alert-error alert-block">
      <button type="button" class="close" data-dismiss="alert">&#215;</button>
      #{messages}
    </div>
    HTML
    html.html_safe
  end

end

app/helpers/buy_actions_helper.rb
module BuyActionsHelper
end

app/helpers/content_items_helper.rb
module ContentItemsHelper
end

app/helpers/downloads_helper.rb
module DownloadsHelper
end

app/helpers/enquiries_helper.rb
module EnquiriesHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/views/content_items/_form.html.erb
<%= simple_form_for(@content_item) do |f| %>
  <%= f.error_notification %>

  
  <div class="form-group">
    <%= f.input :about, input_html: { class: 'form-control ckeditor' } %>
  </div>
  <div class="form-group">
    <%= f.input :quote, input_html: { class: 'form-control' } %>
  </div>
  <div class="form-group">
    <%= f.input :quote_author, input_html: { class: 'form-control' } %>
  </div>
  <div class="form-group">
    <%= f.input :twitter_widget_id, label: 'Twitter widget ID', input_html: { class: 'form-control' } %>
  </div>
  <div class="form-group">
    <%= f.input :trailer_iframe, input_html: { class: 'form-control' } %>
  </div>
  <div class="form-group">
    <%= f.input :trailer_caption, input_html: { class: 'form-control ckeditor' } %>
  </div>

    <%= f.submit 'Update', class: 'btn btn-success' %>
<% end %>

app/views/content_items/edit.html.erb
<h1>Editing content_item</h1>

<%= render 'form' %>

<%= link_to 'Show', @content_item %> |
<%= link_to 'Back', content_items_path %>

app/views/content_items/index.html.erb
<h1>Listing content_items</h1>

<table>
  <thead>
    <tr>
      <th>About</th>
      <th>Quote</th>
      <th>Quote author</th>
      <th>Twitter widget</th>
      <th>Trailer iframe</th>
      <th>Trailer caption</th>
      <th>Download link</th>
      <th>Download image</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @content_items.each do |content_item| %>
      <tr>
        <td><%= content_item.about %></td>
        <td><%= content_item.quote %></td>
        <td><%= content_item.quote_author %></td>
        <td><%= content_item.twitter_widget_id %></td>
        <td><%= content_item.trailer_iframe %></td>
        <td><%= content_item.trailer_caption %></td>
        <td><%= content_item.download_link %></td>
        <td><%= content_item.download_image %></td>
        <td><%= link_to 'Show', content_item %></td>
        <td><%= link_to 'Edit', edit_content_item_path(content_item) %></td>
        <td><%= link_to 'Destroy', content_item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Content item', new_content_item_path %>

app/views/content_items/new.html.erb
<h1>New content_item</h1>

<%= render 'form' %>

<%= link_to 'Back', content_items_path %>

app/views/content_items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>About:</strong>
  <%= @content_item.about %>
</p>

<p>
  <strong>Quote:</strong>
  <%= @content_item.quote %>
</p>

<p>
  <strong>Quote author:</strong>
  <%= @content_item.quote_author %>
</p>

<p>
  <strong>Twitter widget:</strong>
  <%= @content_item.twitter_widget_id %>
</p>

<p>
  <strong>Trailer iframe:</strong>
  <%= @content_item.trailer_iframe %>
</p>

<p>
  <strong>Trailer caption:</strong>
  <%= @content_item.trailer_caption %>
</p>

<p>
  <strong>Download link:</strong>
  <%= @content_item.download_link %>
</p>

<p>
  <strong>Download image:</strong>
  <%= @content_item.download_image %>
</p>

<%= link_to 'Edit', edit_content_item_path(@content_item) %> |
<%= link_to 'Back', content_items_path %>