config/routes.rb
Chik::Application.routes.draw do
  resources :downloads

  resources :images

  resources :enquiries

  get "contact/index"
  resources :buy_actions

  resources :involvement_actions

  resources :events

  resources :background_images

  get "admin" => 'admin#index'
  resources :content_items

  root :to => "home#index"
  devise_for :users, :controllers => {:registrations => "registrations"}
  resources :users
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user 
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. 
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/background_image.rb
class BackgroundImage < ActiveRecord::Base
	default_scope order: 'background_images.priority ASC'
	
	def self.active
		BackgroundImage.where('priority > ?', 0)
	end

	mount_uploader :image, BackgroundImageUploader

	validates_presence_of :priority, :image
end

app/models/buy_action.rb
class BuyAction < ActiveRecord::Base
	default_scope order: 'buy_actions.priority ASC'
	
	def self.active
		BuyAction.where('priority > ?', '0')
	end
end

app/models/content_item.rb
class ContentItem < ActiveRecord::Base
end

app/models/download.rb
class Download < ActiveRecord::Base
end

app/models/enquiry.rb
class Enquiry < ActiveRecord::Base
	validates_presence_of :name, :email, :message
	default_scope order: 'enquiries.created_at DESC'
end

app/models/event.rb
class Event < ActiveRecord::Base
	def self.future
		Event.where("date >= ?", Date.today)
	end

	default_scope order: 'events.date ASC'
end

app/models/image.rb
class Image < ActiveRecord::Base
	mount_uploader :image, PhotoGalleryUploader
end

app/models/involvement_action.rb
class InvolvementAction < ActiveRecord::Base
	default_scope order: 'involvement_actions.priority ASC'
	
	def self.active
		InvolvementAction.where('priority > ?', '0')
	end
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users, :join_table => :users_roles
  belongs_to :resource, :polymorphic => true
  
  scopify
end

app/models/user.rb
class User < ActiveRecord::Base
  rolify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
	layout 'layouts/admin'
	before_filter :authenticate_user!
  def index
  	@content_item = ContentItem.first
  	@background_images = BackgroundImage.all
  	@events = Event.all
  	@buy_actions = BuyAction.all
  	@involvement_actions = InvolvementAction.all
  	@users = User.all
    @image = Image.new
    @images = Image.all
    @download = Download.new
    @downloads = Download.all
  end
end

app/controllers/background_images_controller.rb
class BackgroundImagesController < ApplicationController
  before_filter :authenticate_user!
  before_action :set_background_image, only: [:show, :edit, :update, :destroy]

  # GET /background_images
  # GET /background_images.json
  def index
    @background_images = BackgroundImage.all
  end

  # GET /background_images/1
  # GET /background_images/1.json
  def show
  end

  # GET /background_images/new
  def new
    @background_image = BackgroundImage.new
  end

  # GET /background_images/1/edit
  def edit
  end

  # POST /background_images
  # POST /background_images.json
  def create
    @background_image = BackgroundImage.new(background_image_params)

    respond_to do |format|
      if @background_image.save
        format.html { redirect_to admin_path, notice: 'Background image was successfully created.' }
        format.json { render action: 'show', status: :created, location: @background_image }
      else
        format.html { render action: 'new' }
        format.json { render json: @background_image.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /background_images/1
  # PATCH/PUT /background_images/1.json
  def update
    respond_to do |format|
      if @background_image.update(background_image_params)
        format.html { redirect_to admin_path, notice: 'Background image was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @background_image.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /background_images/1
  # DELETE /background_images/1.json
  def destroy
    @background_image.destroy
    respond_to do |format|
      format.html { redirect_to admin_path }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_background_image
      @background_image = BackgroundImage.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def background_image_params
      params.require(:background_image).permit(:image, :priority)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	layout 'home'
  def index
    @content_item = ContentItem.first
    @event = Event.future.first
    @background_images = BackgroundImage.active
    @buy_actions = BuyAction.active
    @involvement_actions = InvolvementAction.active
    @enquiry = Enquiry.new
    @background_images = BackgroundImage.active
    @images = Image.all
    @downloads = Download.all
  end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

  def display_base_errors resource
    return '' if (resource.errors.empty?) or (resource.errors[:base].empty?)
    messages = resource.errors[:base].map { |msg| content_tag(:p, msg) }.join
    html = <<-HTML
    <div class="alert alert-error alert-block">
      <button type="button" class="close" data-dismiss="alert">&#215;</button>
      #{messages}
    </div>
    HTML
    html.html_safe
  end

end

app/helpers/background_images_helper.rb
module BackgroundImagesHelper
end

app/helpers/buy_actions_helper.rb
module BuyActionsHelper
end

app/helpers/downloads_helper.rb
module DownloadsHelper
end

app/helpers/enquiries_helper.rb
module EnquiriesHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/views/background_images/_form.html.erb
<%= simple_form_for @background_image, html: { multipart: true } do |f| %>
  <%= f.error_notification %>

  <% if @background_image %>
  	<%= image_tag @background_image.image.url, class: 'bg-img-show' %>
  	<br>
  <% end %>
  <br>
  <div class="form-group">
    <%= f.input :image, as: :file, input_html: { class: 'form-control' }, hint: 'Images should be 1200px wide and 750px in height.' %>
  </div>
  <div class="form-group">
    <%= f.input :priority, input_html: { class: 'form-control' }, hint: 'Image 1 will be shown first. Negative numbers makes image inactive.' %>
  </div>

    <%= f.button :submit %>
<% end %>

app/views/background_images/edit.html.erb
<h1>Edit background image</h1>

<div class="well">
			<%= render 'form' %>
		</div>

<%= link_to 'Cancel', admin_path %>

app/views/background_images/index.html.erb
<h1>Listing background_images</h1>

<table>
  <thead>
    <tr>
      <th>Image</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @background_images.each do |background_image| %>
      <tr>
        <td><%= background_image.image %></td>
        <td><%= link_to 'Show', background_image %></td>
        <td><%= link_to 'Edit', edit_background_image_path(background_image) %></td>
        <td><%= link_to 'Destroy', background_image, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Background image', new_background_image_path %>

app/views/background_images/new.html.erb
<h1>New background_image</h1>

<div class="well">
			<%= render 'form' %>
		</div>

<%= link_to 'Cancel', admin_path %>

app/views/background_images/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Image:</strong>
  <%= @background_image.image %>
</p>

<%= link_to 'Edit', edit_background_image_path(@background_image) %> |
<%= link_to 'Back', background_images_path %>