config/routes.rb
Chik::Application.routes.draw do
  resources :downloads

  resources :images

  resources :enquiries

  get "contact/index"
  resources :buy_actions

  resources :involvement_actions

  resources :events

  resources :background_images

  get "admin" => 'admin#index'
  resources :content_items

  root :to => "home#index"
  devise_for :users, :controllers => {:registrations => "registrations"}
  resources :users
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user 
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. 
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/background_image.rb
class BackgroundImage < ActiveRecord::Base
	default_scope order: 'background_images.priority ASC'
	
	def self.active
		BackgroundImage.where('priority > ?', 0)
	end

	mount_uploader :image, BackgroundImageUploader

	validates_presence_of :priority, :image
end

app/models/buy_action.rb
class BuyAction < ActiveRecord::Base
	default_scope order: 'buy_actions.priority ASC'
	
	def self.active
		BuyAction.where('priority > ?', '0')
	end
end

app/models/content_item.rb
class ContentItem < ActiveRecord::Base
end

app/models/download.rb
class Download < ActiveRecord::Base
end

app/models/enquiry.rb
class Enquiry < ActiveRecord::Base
	validates_presence_of :name, :email, :message
	default_scope order: 'enquiries.created_at DESC'
end

app/models/event.rb
class Event < ActiveRecord::Base
	def self.future
		Event.where("date >= ?", Date.today)
	end

	default_scope order: 'events.date ASC'
end

app/models/image.rb
class Image < ActiveRecord::Base
	mount_uploader :image, PhotoGalleryUploader
end

app/models/involvement_action.rb
class InvolvementAction < ActiveRecord::Base
	default_scope order: 'involvement_actions.priority ASC'
	
	def self.active
		InvolvementAction.where('priority > ?', '0')
	end
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users, :join_table => :users_roles
  belongs_to :resource, :polymorphic => true
  
  scopify
end

app/models/user.rb
class User < ActiveRecord::Base
  rolify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
	layout 'layouts/admin'
	before_filter :authenticate_user!
  def index
  	@content_item = ContentItem.first
  	@background_images = BackgroundImage.all
  	@events = Event.all
  	@buy_actions = BuyAction.all
  	@involvement_actions = InvolvementAction.all
  	@users = User.all
    @image = Image.new
    @images = Image.all
    @download = Download.new
    @downloads = Download.all
  end
end

app/controllers/buy_actions_controller.rb
class BuyActionsController < ApplicationController
  before_filter :authenticate_user!
  before_action :set_buy_action, only: [:show, :edit, :update, :destroy]

  # GET /buy_actions
  # GET /buy_actions.json
  def index
    @buy_actions = BuyAction.all
  end

  # GET /buy_actions/1
  # GET /buy_actions/1.json
  def show
  end

  # GET /buy_actions/new
  def new
    @buy_action = BuyAction.new
  end

  # GET /buy_actions/1/edit
  def edit
  end

  # POST /buy_actions
  # POST /buy_actions.json
  def create
    @buy_action = BuyAction.new(buy_action_params)

    respond_to do |format|
      if @buy_action.save
        format.html { redirect_to admin_path, notice: 'Buy action was successfully created.' }
        format.json { render action: 'show', status: :created, location: @buy_action }
      else
        format.html { render action: 'new' }
        format.json { render json: @buy_action.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /buy_actions/1
  # PATCH/PUT /buy_actions/1.json
  def update
    respond_to do |format|
      if @buy_action.update(buy_action_params)
        format.html { redirect_to admin_path, notice: 'Buy action was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @buy_action.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /buy_actions/1
  # DELETE /buy_actions/1.json
  def destroy
    @buy_action.destroy
    respond_to do |format|
      format.html { redirect_to admin_path }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_buy_action
      @buy_action = BuyAction.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def buy_action_params
      params.require(:buy_action).permit(:title, :description, :link, :priority)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	layout 'home'
  def index
    @content_item = ContentItem.first
    @event = Event.future.first
    @background_images = BackgroundImage.active
    @buy_actions = BuyAction.active
    @involvement_actions = InvolvementAction.active
    @enquiry = Enquiry.new
    @background_images = BackgroundImage.active
    @images = Image.all
    @downloads = Download.all
  end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

  def display_base_errors resource
    return '' if (resource.errors.empty?) or (resource.errors[:base].empty?)
    messages = resource.errors[:base].map { |msg| content_tag(:p, msg) }.join
    html = <<-HTML
    <div class="alert alert-error alert-block">
      <button type="button" class="close" data-dismiss="alert">&#215;</button>
      #{messages}
    </div>
    HTML
    html.html_safe
  end

end

app/helpers/buy_actions_helper.rb
module BuyActionsHelper
end

app/helpers/downloads_helper.rb
module DownloadsHelper
end

app/helpers/enquiries_helper.rb
module EnquiriesHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/views/buy_actions/_form.html.erb
<%= simple_form_for(@buy_action) do |f| %>
  <%= f.error_notification %>

  
  <div class="form-group">
    <%= f.input :title, input_html: { class: 'form-control' } %>
  </div>
  <div class="form-group">
    <%= f.input :description, input_html: { class: 'form-control' } %>
  </div>
  <div class="form-group">
    <%= f.input :link, input_html: { class: 'form-control' } %>
  </div>
  <div class="form-group">
    <%= f.input :priority, input_html: { class: 'form-control' } %>
  </div>

    <%= f.submit 'Submit' %>
<% end %>

app/views/buy_actions/edit.html.erb
<h1>Edit purchase option</h1>
<div class="well">
<%= render 'form' %>
</div>
<%= link_to 'Cancel', admin_path %>

app/views/buy_actions/index.html.erb
<h1>Listing buy_actions</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Link</th>
      <th>Priority</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @buy_actions.each do |buy_action| %>
      <tr>
        <td><%= buy_action.title %></td>
        <td><%= buy_action.description %></td>
        <td><%= buy_action.link %></td>
        <td><%= buy_action.priority %></td>
        <td><%= link_to 'Show', buy_action %></td>
        <td><%= link_to 'Edit', edit_buy_action_path(buy_action) %></td>
        <td><%= link_to 'Destroy', buy_action, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Buy action', new_buy_action_path %>

app/views/buy_actions/new.html.erb
<h1>New purchase option</h1>
<div class="well">
<%= render 'form' %>
</div>
<%= link_to 'Cancel', admin_path %>

app/views/buy_actions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @buy_action.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @buy_action.description %>
</p>

<p>
  <strong>Link:</strong>
  <%= @buy_action.link %>
</p>

<p>
  <strong>Priority:</strong>
  <%= @buy_action.priority %>
</p>

<%= link_to 'Edit', edit_buy_action_path(@buy_action) %> |
<%= link_to 'Back', buy_actions_path %>